/**
 * Agent System Type Definitions (UI Package)
 *
 * ContentBlock types (TextBlock, ToolUseBlock, etc.) are now generated by GraphQL codegen.
 * Import from './graphql' or use generated types directly.
 *
 * This file contains only UI-specific types that are not in the GraphQL schema.
 */

/**
 * Pending tool call (UI-specific type for approval workflow)
 * Used by UI components to track tool calls awaiting user approval
 */
export interface PendingToolCall {
  toolCallId: string;
  toolName: string;
  toolInput: any;
  messageId: string;
}
