#!/bin/bash
set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}Starting Local Supabase Development Environment...${NC}\n"

# 1. Check prerequisites
echo -e "${YELLOW}[1/6] Checking prerequisites...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed or not running.${NC}"
    echo "Please install Docker Desktop: https://www.docker.com/products/docker-desktop"
    exit 1
fi

if ! docker info &> /dev/null; then
    echo -e "${RED}Error: Docker daemon is not running.${NC}"
    echo "Please start Docker Desktop and try again."
    exit 1
fi

if ! command -v supabase &> /dev/null; then
    echo -e "${RED}Error: Supabase CLI is not installed.${NC}"
    echo "Install with: brew install supabase/tap/supabase"
    exit 1
fi

echo -e "${GREEN}✓ Prerequisites satisfied${NC}\n"

# 2. Start Supabase
echo -e "${YELLOW}[2/6] Starting local Supabase...${NC}"
cd apps/api

# Check if already running
if supabase status &> /dev/null; then
    echo -e "${GREEN}✓ Supabase already running${NC}\n"
else
    supabase start
    echo -e "${GREEN}✓ Supabase started${NC}\n"
fi

# Get status for connection details
SUPABASE_STATUS=$(supabase status)
cd ../..

# 3. Generate .env.local files
echo -e "${YELLOW}[3/6] Generating .env.local files...${NC}"

# API .env.local
cat > apps/api/.env.local <<EOF
# Local Supabase (auto-generated by scripts/dev-local.sh)
# DO NOT COMMIT THIS FILE

DATABASE_URL="postgresql://postgres:postgres@localhost:54322/postgres"
EOF
echo -e "${GREEN}✓ Created apps/api/.env.local${NC}"

# Web .env.local
cat > apps/web/.env.local <<EOF
# Local Supabase (auto-generated by scripts/dev-local.sh)
# DO NOT COMMIT THIS FILE

NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
EOF
echo -e "${GREEN}✓ Created apps/web/.env.local${NC}\n"

# 4. Push schema to local database
echo -e "${YELLOW}[4/6] Pushing schema to local database...${NC}"
cd apps/api
npm run db:push
cd ../..
echo -e "${GREEN}✓ Schema pushed${NC}\n"

# 5. Display connection info
echo -e "${YELLOW}[5/6] Local Supabase connection info:${NC}"
echo "$SUPABASE_STATUS"
echo ""

# 6. Start dev servers
echo -e "${YELLOW}[6/6] Starting dev servers...${NC}"
echo -e "${GREEN}✓ Local environment ready!${NC}\n"
echo -e "Running: ${GREEN}npm run dev${NC}\n"

npm run dev
